language: node_js
node_js:
  - "stable"

before_install:
  - cd exam/exam

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: exam/exam/build
  on:
    branch:
      - master
      - devel
      - exam
